### PR TITLE
[Bug] 修复语法提示未匹配时导致 NoSuchElementException 的报错问题。Fix the NoSuchElementException error when syntax hint is not matched.

### LINKED ISSUE #1728: 语法提示优化专项
工作量：5d

### PR DESCRIPTION
**Pull request by kaliGo-Li**
Solve the NoSuchElementException that the firstToken and lastToken of LexerUtils.scala trigger None during match

# What changes were proposed in this pull request?
- [ ] Finshed changes describe
Solve the NoSuchElementException that the firstToken and lastToken of LexerUtils.scala trigger None during match
# How was this patch tested?
- [ ] Testing done
截屏2022-03-23 00 07 23
截屏2022-03-23 00 07 55

# Are there and DOC need to update?
- [ ] Doc is finished

# Spark Core Compatibility

### CODE REVIEW

File: external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala [hunk 1]
```diff
@@ -62,23 +63,32 @@ object LexerUtils {
...
+    if((headTokenLineNum)>lineNumList.last){
+      headTokenLineNum=lineNumList.last
+    }
+    if((lastTokenLineNum)>lineNumList.last){
+      lastTokenLineNum=lineNumList.last
+    }
     val firstToken = oneLineTokens.headOption match {
       case Some(head) => head
-      case None =>
+      case None=>
```
Comment (chncaesar) [inline external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala]: Change in this line is not necessary.

File: external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala [hunk 2]
```diff
@@ -62,23 +63,32 @@ object LexerUtils {
     if (tokens.size == 0) {
       return TokenPos(-1, TokenPosType.NEXT, -1)
     }
-
     val oneLineTokens = tokens.zipWithIndex.filter { case (token, index) =>
       token.getLine == lineNum
     }
-
+    var lineNumList:ListBuffer[Int]=ListBuffer[Int]()
```
Comment (chncaesar) [inline external/mlsql-autosuggest/src/main/java/tech/mlsql/autosuggest/statement/LexerUtils.scala]: Please change the code style. For example: `lineNumList=lineNumList.distinct` --> `lineNumList = lineNumList.distinct`

**Review by chncaesar — CHANGES_REQUESTED** [review]
